Add @SteveEmfore models
OpenLoco/OpenGraphics pull request #8
Opened 2024-10-30 21:49 UTC by duncanspumpkin

A selection of trains. I've adjusted them to have OpenLoco source game.

2024-10-31 02:41 UTC, LeftofZen commented
> One item to discuss all of these have (OGFX) in their strings. Should we remove that? I think yes.

Agreed, remove. I would imagine these objects also have the bugged design year?

2024-10-31 06:58 UTC, duncanspumpkin commented
> > One item to discuss all of these have (OGFX) in their strings. Should we remove that? I think yes.
> 
> Agreed, remove. I would imagine these objects also have the bugged design year?

I patched the editor last night and used that when editing to address that issue

2024-11-01 13:15 UTC, LeftofZen commented on objects/Vehicle/Train/JINTY/.gitkeep
I don't see any files added into this folder?

2024-11-01 13:24 UTC, duncanspumpkin commented on objects/Vehicle/Train/JINTY/.gitkeep
Argh did i forget to add it.

2024-11-01 13:27 UTC, LeftofZen requested changes
ST8FT - missing dat file
JINTY - missing dat file and blend file

2024-11-01 13:27 UTC, LeftofZen commented on objects/Vehicle/Train/ST8FT/OGST8F.blend
missing dat file for this object

2024-11-01 13:27 UTC, LeftofZen commented on objects/Vehicle/Train/JINTY/.gitkeep
I don't see any files added into this folder?

2024-11-03 23:58 UTC, duncanspumpkin commented on objects/Vehicle/Train/ST8FT/OGST8F.blend
fixed

2024-11-03 23:58 UTC, duncanspumpkin commented on objects/Vehicle/Train/JINTY/.gitkeep
fixed

2024-11-04 12:23 UTC, LeftofZen approved these changes
approving, on the condition the filename extensions are normalised to `.dat` (there are 2 with `.DAT`)

2024-11-04 16:13 UTC, merged